"""
Kric11 — Hardcoded player data.
Updated for verified 2026 IPL manual roster.
"""

TEAMS = {
    "CSK": "Chennai Super Kings",
    "DC": "Delhi Capitals",
    "GT": "Gujarat Titans",
    "KKR": "Kolkata Knight Riders",
    "LSG": "Lucknow Super Giants",
    "MI": "Mumbai Indians",
    "PBKS": "Punjab Kings",
    "RR": "Rajasthan Royals",
    "RCB": "Royal Challengers Bengaluru",
    "SRH": "Sunrisers Hyderabad",
}

PLAYERS = [
    {"id": 1, "name": "Ruturaj Gaikwad", "role": "BAT", "team": "CSK", "credits": 9.5},
    {"id": 2, "name": "Dewald Brevis", "role": "BAT", "team": "CSK", "credits": 8.5},
    {"id": 3, "name": "Ayush Mhatre", "role": "BAT", "team": "CSK", "credits": 8.0},
    {"id": 4, "name": "Matthew Short", "role": "BAT", "team": "CSK", "credits": 8.5},
    {"id": 5, "name": "Sarfaraz Khan", "role": "BAT", "team": "CSK", "credits": 8.5},
    {"id": 6, "name": "Shivam Dube", "role": "AR", "team": "CSK", "credits": 9.5},
    {"id": 7, "name": "Ramakrishna Ghosh", "role": "AR", "team": "CSK", "credits": 8.5},
    {"id": 8, "name": "Jamie Overton", "role": "AR", "team": "CSK", "credits": 8.5},
    {"id": 9, "name": "Anshul Kamboj", "role": "AR", "team": "CSK", "credits": 8.5},
    {"id": 10, "name": "Prashant Veer", "role": "AR", "team": "CSK", "credits": 8.5},
    {"id": 11, "name": "Zakary Foulkes", "role": "AR", "team": "CSK", "credits": 9.0},
    {"id": 12, "name": "Aman Khan", "role": "AR", "team": "CSK", "credits": 8.5},
    {"id": 13, "name": "MS Dhoni", "role": "WK", "team": "CSK", "credits": 8.0},
    {"id": 14, "name": "Urvil Patel", "role": "WK", "team": "CSK", "credits": 9.5},
    {"id": 15, "name": "Sanju Samson", "role": "WK", "team": "CSK", "credits": 8.0},
    {"id": 16, "name": "Kartik Sharma", "role": "WK", "team": "CSK", "credits": 8.5},
    {"id": 17, "name": "Shreyas Gopal", "role": "BOWL", "team": "CSK", "credits": 8.5},
    {"id": 18, "name": "Khaleel Ahmed", "role": "BOWL", "team": "CSK", "credits": 8.5},
    {"id": 19, "name": "Gurjapneet Singh", "role": "BOWL", "team": "CSK", "credits": 8.0},
    {"id": 20, "name": "Mukesh Choudhary", "role": "BOWL", "team": "CSK", "credits": 8.0},
    {"id": 21, "name": "Noor Ahmad", "role": "BOWL", "team": "CSK", "credits": 9.0},
    {"id": 22, "name": "Akeal Hosein", "role": "BOWL", "team": "CSK", "credits": 8.0},
    {"id": 23, "name": "Matt Henry", "role": "BOWL", "team": "CSK", "credits": 9.0},
    {"id": 24, "name": "Rahul Chahar", "role": "BOWL", "team": "CSK", "credits": 8.0},
    {"id": 25, "name": "Spencer Johnson", "role": "BOWL", "team": "CSK", "credits": 9.5},
    {"id": 26, "name": "Karun Nair", "role": "BAT", "team": "DC", "credits": 9.0},
    {"id": 27, "name": "Nitish Rana", "role": "BAT", "team": "DC", "credits": 9.5},
    {"id": 28, "name": "Sameer Rizvi", "role": "BAT", "team": "DC", "credits": 8.0},
    {"id": 29, "name": "David Miller", "role": "BAT", "team": "DC", "credits": 8.0},
    {"id": 30, "name": "Pathum Nissanka", "role": "BAT", "team": "DC", "credits": 9.5},
    {"id": 31, "name": "Sahil Parakh", "role": "BAT", "team": "DC", "credits": 8.0},
    {"id": 32, "name": "Prithvi Shaw", "role": "BAT", "team": "DC", "credits": 8.0},
    {"id": 33, "name": "Ashutosh Sharma", "role": "AR", "team": "DC", "credits": 9.5},
    {"id": 34, "name": "Axar Patel", "role": "AR", "team": "DC", "credits": 9.0},
    {"id": 35, "name": "Ajay Jadav Mandal", "role": "AR", "team": "DC", "credits": 8.5},
    {"id": 36, "name": "Madhav Tiwari", "role": "AR", "team": "DC", "credits": 8.5},
    {"id": 37, "name": "Tripurana Vijay", "role": "AR", "team": "DC", "credits": 9.5},
    {"id": 38, "name": "Auqib Nabi Dar", "role": "AR", "team": "DC", "credits": 9.0},
    {"id": 39, "name": "Abishek Porel", "role": "WK", "team": "DC", "credits": 8.5},
    {"id": 40, "name": "KL Rahul", "role": "WK", "team": "DC", "credits": 8.0},
    {"id": 41, "name": "Tristan Stubbs", "role": "WK", "team": "DC", "credits": 9.0},
    {"id": 42, "name": "Dushmantha Chameera", "role": "BOWL", "team": "DC", "credits": 9.5},
    {"id": 43, "name": "Kuldeep Yadav", "role": "BOWL", "team": "DC", "credits": 8.5},
    {"id": 44, "name": "Mukesh Kumar", "role": "BOWL", "team": "DC", "credits": 8.0},
    {"id": 45, "name": "T Natarajan", "role": "BOWL", "team": "DC", "credits": 9.5},
    {"id": 46, "name": "Vipraj Nigam", "role": "BOWL", "team": "DC", "credits": 8.0},
    {"id": 47, "name": "Mitchell Starc", "role": "BOWL", "team": "DC", "credits": 9.0},
    {"id": 48, "name": "Lungi Ngidi", "role": "BOWL", "team": "DC", "credits": 9.5},
    {"id": 49, "name": "Kyle Jamieson", "role": "BOWL", "team": "DC", "credits": 8.5},
    {"id": 50, "name": "Shubman Gill", "role": "BAT", "team": "GT", "credits": 8.0},
    {"id": 51, "name": "M Shahrukh Khan", "role": "BAT", "team": "GT", "credits": 9.5},
    {"id": 52, "name": "Sai Sudharsan", "role": "BAT", "team": "GT", "credits": 8.5},
    {"id": 53, "name": "Nishant Sindhu", "role": "AR", "team": "GT", "credits": 9.0},
    {"id": 54, "name": "Rashid Khan", "role": "AR", "team": "GT", "credits": 9.5},
    {"id": 55, "name": "Manav Suthar", "role": "AR", "team": "GT", "credits": 8.0},
    {"id": 56, "name": "Rahul Tewatia", "role": "AR", "team": "GT", "credits": 8.5},
    {"id": 57, "name": "Washington Sundar", "role": "AR", "team": "GT", "credits": 8.5},
    {"id": 58, "name": "Arshad Khan", "role": "AR", "team": "GT", "credits": 9.5},
    {"id": 59, "name": "Ravisrinivasan Sai Kishore", "role": "AR", "team": "GT", "credits": 9.0},
    {"id": 60, "name": "Jason Holder", "role": "AR", "team": "GT", "credits": 8.0},
    {"id": 61, "name": "Anuj Rawat", "role": "WK", "team": "GT", "credits": 9.0},
    {"id": 62, "name": "Jos Buttler", "role": "WK", "team": "GT", "credits": 9.5},
    {"id": 63, "name": "Kumar Kushagra", "role": "WK", "team": "GT", "credits": 9.0},
    {"id": 64, "name": "Glenn Phillips", "role": "WK", "team": "GT", "credits": 9.0},
    {"id": 65, "name": "Tom Banton", "role": "WK", "team": "GT", "credits": 9.0},
    {"id": 66, "name": "Gurnoor Brar", "role": "BOWL", "team": "GT", "credits": 8.0},
    {"id": 67, "name": "Mohammed Siraj", "role": "BOWL", "team": "GT", "credits": 9.0},
    {"id": 68, "name": "Prasidh Krishna", "role": "BOWL", "team": "GT", "credits": 9.5},
    {"id": 69, "name": "Kagiso Rabada", "role": "BOWL", "team": "GT", "credits": 8.5},
    {"id": 70, "name": "Jayant Yadav", "role": "BOWL", "team": "GT", "credits": 8.0},
    {"id": 71, "name": "Ishant Sharma", "role": "BOWL", "team": "GT", "credits": 8.5},
    {"id": 72, "name": "Ashok Sharma", "role": "BOWL", "team": "GT", "credits": 8.0},
    {"id": 73, "name": "Luke Wood", "role": "BOWL", "team": "GT", "credits": 8.5},
    {"id": 74, "name": "Kulwant Khejroliya", "role": "BOWL", "team": "GT", "credits": 9.0},
    {"id": 75, "name": "Rajat Patidar", "role": "BAT", "team": "RCB", "credits": 8.5},
    {"id": 76, "name": "Tim David", "role": "BAT", "team": "RCB", "credits": 8.5},
    {"id": 77, "name": "Virat Kohli", "role": "BAT", "team": "RCB", "credits": 9.5},
    {"id": 78, "name": "Devdutt Padikkal", "role": "BAT", "team": "RCB", "credits": 8.0},
    {"id": 79, "name": "Jacob Bethell", "role": "AR", "team": "RCB", "credits": 8.5},
    {"id": 80, "name": "Krunal Pandya", "role": "AR", "team": "RCB", "credits": 8.5},
    {"id": 81, "name": "Venkatesh Iyer", "role": "AR", "team": "RCB", "credits": 9.0},
    {"id": 82, "name": "Vihaan Malhotra", "role": "AR", "team": "RCB", "credits": 9.5},
    {"id": 83, "name": "Romario Shepherd", "role": "AR", "team": "RCB", "credits": 8.0},
    {"id": 84, "name": "Mangesh Yadav", "role": "AR", "team": "RCB", "credits": 8.5},
    {"id": 85, "name": "Kanishk Chouhan", "role": "AR", "team": "RCB", "credits": 9.5},
    {"id": 86, "name": "Satvik Deswal", "role": "AR", "team": "RCB", "credits": 8.5},
    {"id": 87, "name": "Philip Salt", "role": "WK", "team": "RCB", "credits": 9.5},
    {"id": 88, "name": "Jitesh Sharma", "role": "WK", "team": "RCB", "credits": 8.5},
    {"id": 89, "name": "Jordan Cox", "role": "WK", "team": "RCB", "credits": 9.0},
    {"id": 90, "name": "Abhinandan Singh", "role": "BOWL", "team": "RCB", "credits": 8.0},
    {"id": 91, "name": "Josh Hazlewood", "role": "BOWL", "team": "RCB", "credits": 9.0},
    {"id": 92, "name": "Rasikh Salam Dar", "role": "BOWL", "team": "RCB", "credits": 8.0},
    {"id": 93, "name": "Bhuvneshwar Kumar", "role": "BOWL", "team": "RCB", "credits": 8.5},
    {"id": 94, "name": "Suyash Sharma", "role": "BOWL", "team": "RCB", "credits": 8.5},
    {"id": 95, "name": "Swapnil Singh", "role": "BOWL", "team": "RCB", "credits": 8.5},
    {"id": 96, "name": "Nuwan Thushara", "role": "BOWL", "team": "RCB", "credits": 9.0},
    {"id": 97, "name": "Jacob Duffy", "role": "BOWL", "team": "RCB", "credits": 9.5},
    {"id": 98, "name": "Vicky Ostwal", "role": "BOWL", "team": "RCB", "credits": 8.0},
    {"id": 99, "name": "Shreyas Iyer", "role": "BAT", "team": "PBKS", "credits": 8.0},
    {"id": 100, "name": "Priyansh Arya", "role": "BAT", "team": "PBKS", "credits": 8.5},
    {"id": 101, "name": "Pyla Avinash", "role": "BAT", "team": "PBKS", "credits": 8.0},
    {"id": 102, "name": "Harnoor Singh", "role": "BAT", "team": "PBKS", "credits": 8.5},
    {"id": 103, "name": "Nehal Wadhera", "role": "BAT", "team": "PBKS", "credits": 8.5},
    {"id": 104, "name": "Mitchell Owen", "role": "AR", "team": "PBKS", "credits": 8.5},
    {"id": 105, "name": "Musheer Khan", "role": "AR", "team": "PBKS", "credits": 8.0},
    {"id": 106, "name": "Shashank Singh", "role": "AR", "team": "PBKS", "credits": 9.0},
    {"id": 107, "name": "Marcus Stoinis", "role": "AR", "team": "PBKS", "credits": 9.0},
    {"id": 108, "name": "Suryansh Shedge", "role": "AR", "team": "PBKS", "credits": 9.5},
    {"id": 109, "name": "Cooper Connolly", "role": "AR", "team": "PBKS", "credits": 9.5},
    {"id": 110, "name": "Azmatullah Omarzai", "role": "AR", "team": "PBKS", "credits": 9.0},
    {"id": 111, "name": "Marco Jansen", "role": "AR", "team": "PBKS", "credits": 8.0},
    {"id": 112, "name": "Praveen Dubey", "role": "AR", "team": "PBKS", "credits": 8.5},
    {"id": 113, "name": "Prabhsimran Singh", "role": "WK", "team": "PBKS", "credits": 8.5},
    {"id": 114, "name": "Vishnu Vinod", "role": "WK", "team": "PBKS", "credits": 8.0},
    {"id": 115, "name": "Arshdeep Singh", "role": "BOWL", "team": "PBKS", "credits": 9.0},
    {"id": 116, "name": "Xavier Bartlett", "role": "BOWL", "team": "PBKS", "credits": 9.5},
    {"id": 117, "name": "Yuzvendra Chahal", "role": "BOWL", "team": "PBKS", "credits": 8.0},
    {"id": 118, "name": "Lockie Ferguson", "role": "BOWL", "team": "PBKS", "credits": 9.5},
    {"id": 119, "name": "Harpreet Brar", "role": "BOWL", "team": "PBKS", "credits": 8.5},
    {"id": 120, "name": "Vijaykumar Vyshak", "role": "BOWL", "team": "PBKS", "credits": 8.5},
    {"id": 121, "name": "Yash Thakur", "role": "BOWL", "team": "PBKS", "credits": 9.5},
    {"id": 122, "name": "Ben Dwarshuis", "role": "BOWL", "team": "PBKS", "credits": 8.5},
    {"id": 123, "name": "Vishal Nishad", "role": "BOWL", "team": "PBKS", "credits": 8.5},
    {"id": 124, "name": "Angkrish Raghuvanshi", "role": "BAT", "team": "KKR", "credits": 8.0},
    {"id": 125, "name": "Rinku Singh", "role": "BAT", "team": "KKR", "credits": 9.5},
    {"id": 126, "name": "Finn Allen", "role": "BAT", "team": "KKR", "credits": 9.0},
    {"id": 127, "name": "Rahul Tripathi", "role": "BAT", "team": "KKR", "credits": 9.0},
    {"id": 128, "name": "Sarthak Ranjan", "role": "BAT", "team": "KKR", "credits": 9.0},
    {"id": 129, "name": "Ramandeep Singh", "role": "AR", "team": "KKR", "credits": 9.5},
    {"id": 130, "name": "Anukul Roy", "role": "AR", "team": "KKR", "credits": 9.0},
    {"id": 131, "name": "Cameron Green", "role": "AR", "team": "KKR", "credits": 8.5},
    {"id": 132, "name": "Rachin Ravindra", "role": "AR", "team": "KKR", "credits": 9.5},
    {"id": 133, "name": "Sunil Narine", "role": "AR", "team": "KKR", "credits": 8.0},
    {"id": 134, "name": "Daksh Kamra", "role": "AR", "team": "KKR", "credits": 9.5},
    {"id": 135, "name": "Tim Seifert", "role": "WK", "team": "KKR", "credits": 9.5},
    {"id": 136, "name": "Tejasvi Dahiya", "role": "WK", "team": "KKR", "credits": 9.0},
    {"id": 137, "name": "Vaibhav Arora", "role": "BOWL", "team": "KKR", "credits": 8.5},
    {"id": 138, "name": "Umran Malik", "role": "BOWL", "team": "KKR", "credits": 9.5},
    {"id": 139, "name": "Varun Chakaravarthy", "role": "BOWL", "team": "KKR", "credits": 9.5},
    {"id": 140, "name": "Prashant Solanki", "role": "BOWL", "team": "KKR", "credits": 8.0},
    {"id": 141, "name": "Kartik Tyagi", "role": "BOWL", "team": "KKR", "credits": 8.0},
    {"id": 142, "name": "Matheesha Pathirana", "role": "BOWL", "team": "KKR", "credits": 9.5},
    {"id": 143, "name": "Blessing Muzarabani", "role": "BOWL", "team": "KKR", "credits": 9.5},
    {"id": 144, "name": "Saurabh Dubey", "role": "BOWL", "team": "KKR", "credits": 8.5},
    {"id": 145, "name": "Navdeep Saini", "role": "BOWL", "team": "KKR", "credits": 8.5},
    {"id": 146, "name": "Travis Head", "role": "BAT", "team": "SRH", "credits": 9.5},
    {"id": 147, "name": "Smaran Ravichandran", "role": "BAT", "team": "SRH", "credits": 9.5},
    {"id": 148, "name": "Aniket Verma", "role": "BAT", "team": "SRH", "credits": 8.0},
    {"id": 149, "name": "Abhishek Sharma", "role": "AR", "team": "SRH", "credits": 9.5},
    {"id": 150, "name": "Kamindu Mendis", "role": "AR", "team": "SRH", "credits": 9.0},
    {"id": 151, "name": "Nitish Kumar Reddy", "role": "AR", "team": "SRH", "credits": 9.0},
    {"id": 152, "name": "Liam Livingstone", "role": "AR", "team": "SRH", "credits": 8.0},
    {"id": 153, "name": "Harsh Dubey", "role": "AR", "team": "SRH", "credits": 9.5},
    {"id": 154, "name": "Shivang Kumar", "role": "AR", "team": "SRH", "credits": 8.5},
    {"id": 155, "name": "Ishan Kishan", "role": "WK", "team": "SRH", "credits": 8.0},
    {"id": 156, "name": "Heinrich Klaasen", "role": "WK", "team": "SRH", "credits": 8.0},
    {"id": 157, "name": "Salil Arora", "role": "WK", "team": "SRH", "credits": 9.5},
    {"id": 158, "name": "Brydon Carse", "role": "BOWL", "team": "SRH", "credits": 8.0},
    {"id": 159, "name": "Pat Cummins", "role": "BOWL", "team": "SRH", "credits": 9.5},
    {"id": 160, "name": "Eshan Malinga", "role": "BOWL", "team": "SRH", "credits": 8.5},
    {"id": 161, "name": "Jaydev Unadkat", "role": "BOWL", "team": "SRH", "credits": 9.0},
    {"id": 162, "name": "Harshal Patel", "role": "BOWL", "team": "SRH", "credits": 8.5},
    {"id": 163, "name": "Zeeshan Ansari", "role": "BOWL", "team": "SRH", "credits": 9.0},
    {"id": 164, "name": "Sakib Hussain", "role": "BOWL", "team": "SRH", "credits": 8.5},
    {"id": 165, "name": "Omkar Tukaram Tarmale", "role": "BOWL", "team": "SRH", "credits": 8.5},
    {"id": 166, "name": "Amit Kumar", "role": "BOWL", "team": "SRH", "credits": 9.0},
    {"id": 167, "name": "Praful Hinge", "role": "BOWL", "team": "SRH", "credits": 8.0},
    {"id": 168, "name": "Krish Fuletra", "role": "BOWL", "team": "SRH", "credits": 8.5},
    {"id": 169, "name": "Shivam Mavi", "role": "BOWL", "team": "SRH", "credits": 9.5},
    {"id": 170, "name": "David Payne", "role": "BOWL", "team": "SRH", "credits": 9.5},
    {"id": 171, "name": "Shubham Dubey", "role": "BAT", "team": "RR", "credits": 8.5},
    {"id": 172, "name": "Shimron Hetmyer", "role": "BAT", "team": "RR", "credits": 9.5},
    {"id": 173, "name": "Yashasvi Jaiswal", "role": "BAT", "team": "RR", "credits": 8.0},
    {"id": 174, "name": "Vaibhav Sooryavanshi", "role": "BAT", "team": "RR", "credits": 8.0},
    {"id": 175, "name": "Aman Rao Perala", "role": "BAT", "team": "RR", "credits": 9.5},
    {"id": 176, "name": "Riyan Parag", "role": "AR", "team": "RR", "credits": 9.5},
    {"id": 177, "name": "Dasun Shanaka", "role": "AR", "team": "RR", "credits": 8.5},
    {"id": 178, "name": "Ravindra Jadeja", "role": "AR", "team": "RR", "credits": 9.5},
    {"id": 179, "name": "Dhruv Jurel", "role": "WK", "team": "RR", "credits": 9.5},
    {"id": 180, "name": "Lhuan-dre Pretorius", "role": "WK", "team": "RR", "credits": 9.5},
    {"id": 181, "name": "Donovan Ferreira", "role": "WK", "team": "RR", "credits": 8.0},
    {"id": 182, "name": "Ravi Singh", "role": "WK", "team": "RR", "credits": 9.0},
    {"id": 183, "name": "Jofra Archer", "role": "BOWL", "team": "RR", "credits": 8.0},
    {"id": 184, "name": "Nandre Burger", "role": "BOWL", "team": "RR", "credits": 8.5},
    {"id": 185, "name": "Tushar Deshpande", "role": "BOWL", "team": "RR", "credits": 8.0},
    {"id": 186, "name": "Kwena Maphaka", "role": "BOWL", "team": "RR", "credits": 8.5},
    {"id": 187, "name": "Sandeep Sharma", "role": "BOWL", "team": "RR", "credits": 9.0},
    {"id": 188, "name": "Yudhvir Singh Charak", "role": "BOWL", "team": "RR", "credits": 8.0},
    {"id": 189, "name": "Vignesh Puthur", "role": "BOWL", "team": "RR", "credits": 9.0},
    {"id": 190, "name": "Yash Raj Punja", "role": "BOWL", "team": "RR", "credits": 9.0},
    {"id": 191, "name": "Sushant Mishra", "role": "BOWL", "team": "RR", "credits": 9.0},
    {"id": 192, "name": "Ravi Bishnoi", "role": "BOWL", "team": "RR", "credits": 8.0},
    {"id": 193, "name": "Brijesh Sharma", "role": "BOWL", "team": "RR", "credits": 9.0},
    {"id": 194, "name": "Adam Milne", "role": "BOWL", "team": "RR", "credits": 9.0},
    {"id": 195, "name": "Kuldeep Sen", "role": "BOWL", "team": "RR", "credits": 9.5},
    {"id": 196, "name": "Himmat Singh", "role": "BAT", "team": "LSG", "credits": 8.0},
    {"id": 197, "name": "Aiden Markram", "role": "BAT", "team": "LSG", "credits": 8.5},
    {"id": 198, "name": "Akshat Raghuwanshi", "role": "BAT", "team": "LSG", "credits": 9.0},
    {"id": 199, "name": "Abdul Samad", "role": "AR", "team": "LSG", "credits": 9.5},
    {"id": 200, "name": "Ayush Badoni", "role": "AR", "team": "LSG", "credits": 8.0},
    {"id": 201, "name": "Arshin Kulkarni", "role": "AR", "team": "LSG", "credits": 9.5},
    {"id": 202, "name": "Mitchell Marsh", "role": "AR", "team": "LSG", "credits": 9.0},
    {"id": 203, "name": "Shahbaz Ahmed", "role": "AR", "team": "LSG", "credits": 8.5},
    {"id": 204, "name": "Arjun Sachin Tendulkar", "role": "AR", "team": "LSG", "credits": 9.0},
    {"id": 205, "name": "Wanindu Hasaranga", "role": "AR", "team": "LSG", "credits": 8.5},
    {"id": 206, "name": "Rishabh Pant", "role": "WK", "team": "LSG", "credits": 8.0},
    {"id": 207, "name": "Matthew Breetzke", "role": "WK", "team": "LSG", "credits": 8.0},
    {"id": 208, "name": "Nicholas Pooran", "role": "WK", "team": "LSG", "credits": 9.5},
    {"id": 209, "name": "Mukul Choudhary", "role": "WK", "team": "LSG", "credits": 9.5},
    {"id": 210, "name": "Josh Inglis", "role": "WK", "team": "LSG", "credits": 9.5},
    {"id": 211, "name": "Akash Maharaj Singh", "role": "BOWL", "team": "LSG", "credits": 9.5},
    {"id": 212, "name": "Avesh Khan", "role": "BOWL", "team": "LSG", "credits": 9.0},
    {"id": 213, "name": "Mohammed Shami", "role": "BOWL", "team": "LSG", "credits": 9.0},
    {"id": 214, "name": "Prince Yadav", "role": "BOWL", "team": "LSG", "credits": 8.0},
    {"id": 215, "name": "Mohsin Khan", "role": "BOWL", "team": "LSG", "credits": 9.5},
    {"id": 216, "name": "Digvesh Singh Rathi", "role": "BOWL", "team": "LSG", "credits": 9.5},
    {"id": 217, "name": "Manimaran Siddharth", "role": "BOWL", "team": "LSG", "credits": 9.5},
    {"id": 218, "name": "Mayank Prabhu Yadav", "role": "BOWL", "team": "LSG", "credits": 9.5},
    {"id": 219, "name": "Anrich Nortje", "role": "BOWL", "team": "LSG", "credits": 8.5},
    {"id": 220, "name": "Naman Tiwari", "role": "BOWL", "team": "LSG", "credits": 8.0},
    {"id": 221, "name": "Rohit Sharma", "role": "BAT", "team": "MI", "credits": 8.0},
    {"id": 222, "name": "Suryakumar Yadav", "role": "BAT", "team": "MI", "credits": 8.0},
    {"id": 223, "name": "Tilak Varma", "role": "BAT", "team": "MI", "credits": 9.5},
    {"id": 224, "name": "Danish Malewar", "role": "BAT", "team": "MI", "credits": 9.0},
    {"id": 225, "name": "Sherfane Rutherford", "role": "AR", "team": "MI", "credits": 9.5},
    {"id": 226, "name": "Hardik Pandya", "role": "AR", "team": "MI", "credits": 8.5},
    {"id": 227, "name": "Raj Bawa", "role": "AR", "team": "MI", "credits": 8.0},
    {"id": 228, "name": "Will Jacks", "role": "AR", "team": "MI", "credits": 9.0},
    {"id": 229, "name": "Mayank Rawat", "role": "AR", "team": "MI", "credits": 8.0},
    {"id": 230, "name": "Corbin Bosch", "role": "AR", "team": "MI", "credits": 8.0},
    {"id": 231, "name": "Mitchell Santner", "role": "AR", "team": "MI", "credits": 8.0},
    {"id": 232, "name": "Shardul Thakur", "role": "AR", "team": "MI", "credits": 9.0},
    {"id": 233, "name": "Atharva Ankolekar", "role": "AR", "team": "MI", "credits": 8.5},
    {"id": 234, "name": "Robin Minz", "role": "WK", "team": "MI", "credits": 9.0},
    {"id": 235, "name": "Ryan Rickelton", "role": "WK", "team": "MI", "credits": 9.0},
    {"id": 236, "name": "Quinton de Kock", "role": "WK", "team": "MI", "credits": 9.5},
    {"id": 237, "name": "Trent Boult", "role": "BOWL", "team": "MI", "credits": 9.5},
    {"id": 238, "name": "Ashwani Kumar", "role": "BOWL", "team": "MI", "credits": 8.5},
    {"id": 239, "name": "Jasprit Bumrah", "role": "BOWL", "team": "MI", "credits": 9.0},
    {"id": 240, "name": "Deepak Chahar", "role": "BOWL", "team": "MI", "credits": 8.5},
    {"id": 241, "name": "Mayank Markande", "role": "BOWL", "team": "MI", "credits": 9.5},
    {"id": 242, "name": "AM Ghazanfar", "role": "BOWL", "team": "MI", "credits": 8.0},
    {"id": 243, "name": "Raghu Sharma", "role": "BOWL", "team": "MI", "credits": 8.0},
    {"id": 244, "name": "Mohammed Salahuddin Izhar", "role": "BOWL", "team": "MI", "credits": 8.5},
]

PLAYERS_BY_ID = {p['id']: p for p in PLAYERS}

USERS = {}
DRAFTS = {}
LOCKED_TEAMS = {}
BUDGET_LIMIT = 100.0
MAX_PLAYERS = 11
