"""
Kric11 — Hardcoded player data.
Updated for verified 2026 IPL manual roster.
"""

TEAMS = {
    "CSK": "Chennai Super Kings",
    "DC": "Delhi Capitals",
    "GT": "Gujarat Titans",
    "KKR": "Kolkata Knight Riders",
    "LSG": "Lucknow Super Giants",
    "MI": "Mumbai Indians",
    "PBKS": "Punjab Kings",
    "RR": "Rajasthan Royals",
    "RCB": "Royal Challengers Bengaluru",
    "SRH": "Sunrisers Hyderabad",
}

PLAYERS = [
    {"id": 1, "name": "Ruturaj Gaikwad", "role": "BAT", "team": "CSK", "credits": 9.5},
    {"id": 2, "name": "MS Dhoni", "role": "WK", "team": "CSK", "credits": 8.0},
    {"id": 3, "name": "Ravindra Jadeja", "role": "AR", "team": "CSK", "credits": 9.5},
    {"id": 4, "name": "Matheesha Pathirana", "role": "BOWL", "team": "CSK", "credits": 9.5},
    {"id": 5, "name": "Ravichandran Ashwin", "role": "AR", "team": "CSK", "credits": 9.5},
    {"id": 6, "name": "Khaleel Ahmed", "role": "BOWL", "team": "CSK", "credits": 8.5},
    {"id": 7, "name": "Rahul Tripathi", "role": "BAT", "team": "CSK", "credits": 9.0},
    {"id": 8, "name": "Sam Curran", "role": "AR", "team": "CSK", "credits": 9.0},
    {"id": 9, "name": "Devon Conway", "role": "WK", "team": "CSK", "credits": 8.0},
    {"id": 10, "name": "Vijay Shankar", "role": "AR", "team": "CSK", "credits": 8.5},
    {"id": 11, "name": "Rachin Ravindra", "role": "AR", "team": "CSK", "credits": 9.5},
    {"id": 12, "name": "Mukesh Choudhary", "role": "BOWL", "team": "CSK", "credits": 8.0},
    {"id": 13, "name": "Deepak Hooda", "role": "AR", "team": "CSK", "credits": 8.0},
    {"id": 14, "name": "Jamie Overton", "role": "AR", "team": "CSK", "credits": 8.5},
    {"id": 15, "name": "Shaik Rasheed", "role": "BAT", "team": "CSK", "credits": 8.5},
    {"id": 16, "name": "Axar Patel", "role": "AR", "team": "DC", "credits": 9.0},
    {"id": 17, "name": "Kuldeep Yadav", "role": "BOWL", "team": "DC", "credits": 8.5},
    {"id": 18, "name": "Tristan Stubbs", "role": "WK", "team": "DC", "credits": 9.0},
    {"id": 19, "name": "Abishek Porel", "role": "WK", "team": "DC", "credits": 8.5},
    {"id": 20, "name": "KL Rahul", "role": "WK", "team": "DC", "credits": 8.0},
    {"id": 21, "name": "Mitchell Starc", "role": "BOWL", "team": "DC", "credits": 9.0},
    {"id": 22, "name": "Jake Fraser-McGurk", "role": "BAT", "team": "DC", "credits": 9.0},
    {"id": 23, "name": "Faf du Plessis", "role": "BAT", "team": "DC", "credits": 9.0},
    {"id": 24, "name": "T Natarajan", "role": "BOWL", "team": "DC", "credits": 9.5},
    {"id": 25, "name": "Harry Brook", "role": "BAT", "team": "DC", "credits": 9.5},
    {"id": 26, "name": "Mukesh Kumar", "role": "BOWL", "team": "DC", "credits": 8.0},
    {"id": 27, "name": "Sameer Rizvi", "role": "BAT", "team": "DC", "credits": 8.0},
    {"id": 28, "name": "Ashutosh Sharma", "role": "BAT", "team": "DC", "credits": 9.5},
    {"id": 29, "name": "Rashid Khan", "role": "BOWL", "team": "GT", "credits": 9.5},
    {"id": 30, "name": "Shubman Gill", "role": "BAT", "team": "GT", "credits": 8.0},
    {"id": 31, "name": "Sai Sudharsan", "role": "BAT", "team": "GT", "credits": 8.5},
    {"id": 32, "name": "Rahul Tewatia", "role": "AR", "team": "GT", "credits": 8.5},
    {"id": 33, "name": "Shahrukh Khan", "role": "BAT", "team": "GT", "credits": 8.5},
    {"id": 34, "name": "Kagiso Rabada", "role": "BOWL", "team": "GT", "credits": 8.5},
    {"id": 35, "name": "Mohammed Siraj", "role": "BOWL", "team": "GT", "credits": 9.0},
    {"id": 36, "name": "Washington Sundar", "role": "AR", "team": "GT", "credits": 8.5},
    {"id": 37, "name": "Prasidh Krishna", "role": "BOWL", "team": "GT", "credits": 9.5},
    {"id": 38, "name": "Jos Buttler", "role": "WK", "team": "GT", "credits": 9.5},
    {"id": 39, "name": "Glenn Phillips", "role": "WK", "team": "GT", "credits": 9.0},
    {"id": 40, "name": "Ishan Kishan", "role": "WK", "team": "GT", "credits": 8.0},
    {"id": 41, "name": "Gerald Coetzee", "role": "BOWL", "team": "GT", "credits": 9.0},
    {"id": 42, "name": "Rinku Singh", "role": "BAT", "team": "KKR", "credits": 9.5},
    {"id": 43, "name": "Varun Chakaravarthy", "role": "BOWL", "team": "KKR", "credits": 9.5},
    {"id": 44, "name": "Sunil Narine", "role": "AR", "team": "KKR", "credits": 8.0},
    {"id": 45, "name": "Andre Russell", "role": "AR", "team": "KKR", "credits": 8.5},
    {"id": 46, "name": "Harshit Rana", "role": "BOWL", "team": "KKR", "credits": 8.0},
    {"id": 47, "name": "Ramandeep Singh", "role": "AR", "team": "KKR", "credits": 9.5},
    {"id": 48, "name": "Venkatesh Iyer", "role": "AR", "team": "KKR", "credits": 9.0},
    {"id": 49, "name": "Quinton de Kock", "role": "WK", "team": "KKR", "credits": 9.5},
    {"id": 50, "name": "Anrich Nortje", "role": "BOWL", "team": "KKR", "credits": 8.5},
    {"id": 51, "name": "Manish Pandey", "role": "BAT", "team": "KKR", "credits": 8.5},
    {"id": 52, "name": "Rahmanullah Gurbaz", "role": "WK", "team": "KKR", "credits": 9.0},
    {"id": 53, "name": "Rovman Powell", "role": "BAT", "team": "KKR", "credits": 8.5},
    {"id": 54, "name": "Nicholas Pooran", "role": "WK", "team": "LSG", "credits": 9.5},
    {"id": 55, "name": "Ravi Bishnoi", "role": "BOWL", "team": "LSG", "credits": 8.0},
    {"id": 56, "name": "Mayank Yadav", "role": "BOWL", "team": "LSG", "credits": 8.0},
    {"id": 57, "name": "Mohsin Khan", "role": "BOWL", "team": "LSG", "credits": 9.5},
    {"id": 58, "name": "Ayush Badoni", "role": "BAT", "team": "LSG", "credits": 8.0},
    {"id": 59, "name": "Rishabh Pant", "role": "WK", "team": "LSG", "credits": 8.0},
    {"id": 60, "name": "David Miller", "role": "BAT", "team": "LSG", "credits": 8.0},
    {"id": 61, "name": "Aiden Markram", "role": "BAT", "team": "LSG", "credits": 8.5},
    {"id": 62, "name": "Mitchell Marsh", "role": "AR", "team": "LSG", "credits": 9.0},
    {"id": 63, "name": "Abdul Samad", "role": "BAT", "team": "LSG", "credits": 9.5},
    {"id": 64, "name": "Avesh Khan", "role": "BOWL", "team": "LSG", "credits": 9.0},
    {"id": 65, "name": "Akash Deep", "role": "BOWL", "team": "LSG", "credits": 9.0},
    {"id": 66, "name": "Jasprit Bumrah", "role": "BOWL", "team": "MI", "credits": 9.0},
    {"id": 67, "name": "Suryakumar Yadav", "role": "BAT", "team": "MI", "credits": 8.0},
    {"id": 68, "name": "Hardik Pandya", "role": "AR", "team": "MI", "credits": 8.5},
    {"id": 69, "name": "Rohit Sharma", "role": "BAT", "team": "MI", "credits": 8.0},
    {"id": 70, "name": "Tilak Varma", "role": "BAT", "team": "MI", "credits": 9.5},
    {"id": 71, "name": "Trent Boult", "role": "BOWL", "team": "MI", "credits": 9.5},
    {"id": 72, "name": "Naman Dhir", "role": "AR", "team": "MI", "credits": 9.0},
    {"id": 73, "name": "Robin Minz", "role": "WK", "team": "MI", "credits": 9.0},
    {"id": 74, "name": "Will Jacks", "role": "AR", "team": "MI", "credits": 9.0},
    {"id": 75, "name": "Ryan Rickelton", "role": "WK", "team": "MI", "credits": 9.0},
    {"id": 76, "name": "Karn Sharma", "role": "BOWL", "team": "MI", "credits": 9.5},
    {"id": 77, "name": "Deepak Chahar", "role": "BOWL", "team": "MI", "credits": 8.5},
    {"id": 78, "name": "Mitchell Santner", "role": "AR", "team": "MI", "credits": 8.0},
    {"id": 79, "name": "Shashank Singh", "role": "BAT", "team": "PBKS", "credits": 9.0},
    {"id": 80, "name": "Prabhsimran Singh", "role": "WK", "team": "PBKS", "credits": 8.5},
    {"id": 81, "name": "Shreyas Iyer", "role": "BAT", "team": "PBKS", "credits": 8.0},
    {"id": 82, "name": "Arshdeep Singh", "role": "BOWL", "team": "PBKS", "credits": 9.0},
    {"id": 83, "name": "Yuzvendra Chahal", "role": "BOWL", "team": "PBKS", "credits": 8.0},
    {"id": 84, "name": "Marcus Stoinis", "role": "AR", "team": "PBKS", "credits": 9.0},
    {"id": 85, "name": "Glenn Maxwell", "role": "AR", "team": "PBKS", "credits": 8.5},
    {"id": 86, "name": "Nehal Wadhera", "role": "BAT", "team": "PBKS", "credits": 8.5},
    {"id": 87, "name": "Harshal Patel", "role": "BOWL", "team": "PBKS", "credits": 8.5},
    {"id": 88, "name": "Aaron Hardie", "role": "AR", "team": "PBKS", "credits": 8.0},
    {"id": 89, "name": "Marco Jansen", "role": "AR", "team": "PBKS", "credits": 8.0},
    {"id": 90, "name": "Piyush Chawla", "role": "BOWL", "team": "PBKS", "credits": 8.5},
    {"id": 91, "name": "Josh Inglis", "role": "WK", "team": "PBKS", "credits": 9.5},
    {"id": 92, "name": "Sanju Samson", "role": "WK", "team": "RR", "credits": 8.0},
    {"id": 93, "name": "Yashasvi Jaiswal", "role": "BAT", "team": "RR", "credits": 8.0},
    {"id": 94, "name": "Riyan Parag", "role": "BAT", "team": "RR", "credits": 9.5},
    {"id": 95, "name": "Dhruv Jurel", "role": "WK", "team": "RR", "credits": 9.5},
    {"id": 96, "name": "Shimron Hetmyer", "role": "BAT", "team": "RR", "credits": 9.5},
    {"id": 97, "name": "Sandeep Sharma", "role": "BOWL", "team": "RR", "credits": 9.0},
    {"id": 98, "name": "Jofra Archer", "role": "BOWL", "team": "RR", "credits": 8.0},
    {"id": 99, "name": "Maheesh Theekshana", "role": "BOWL", "team": "RR", "credits": 9.0},
    {"id": 100, "name": "Wanindu Hasaranga", "role": "AR", "team": "RR", "credits": 8.5},
    {"id": 101, "name": "Nitish Rana", "role": "BAT", "team": "RR", "credits": 9.5},
    {"id": 102, "name": "Tushar Deshpande", "role": "BOWL", "team": "RR", "credits": 8.0},
    {"id": 103, "name": "Akash Madhwal", "role": "BOWL", "team": "RR", "credits": 8.5},
    {"id": 104, "name": "Fazalhaq Farooqi", "role": "BOWL", "team": "RR", "credits": 8.0},
    {"id": 105, "name": "Virat Kohli", "role": "BAT", "team": "RCB", "credits": 9.5},
    {"id": 106, "name": "Rajat Patidar", "role": "BAT", "team": "RCB", "credits": 8.5},
    {"id": 107, "name": "Yash Dayal", "role": "BOWL", "team": "RCB", "credits": 9.0},
    {"id": 108, "name": "Phil Salt", "role": "WK", "team": "RCB", "credits": 8.5},
    {"id": 109, "name": "Jitesh Sharma", "role": "WK", "team": "RCB", "credits": 8.5},
    {"id": 110, "name": "Liam Livingstone", "role": "AR", "team": "RCB", "credits": 8.0},
    {"id": 111, "name": "Josh Hazlewood", "role": "BOWL", "team": "RCB", "credits": 9.0},
    {"id": 112, "name": "Rasikh Salam", "role": "BOWL", "team": "RCB", "credits": 8.0},
    {"id": 113, "name": "Suyash Sharma", "role": "BOWL", "team": "RCB", "credits": 8.5},
    {"id": 114, "name": "Krunal Pandya", "role": "AR", "team": "RCB", "credits": 8.5},
    {"id": 115, "name": "Bhuvneshwar Kumar", "role": "BOWL", "team": "RCB", "credits": 8.5},
    {"id": 116, "name": "Tim David", "role": "BAT", "team": "RCB", "credits": 8.5},
    {"id": 117, "name": "Devdutt Padikkal", "role": "BAT", "team": "RCB", "credits": 8.0},
    {"id": 118, "name": "Heinrich Klaasen", "role": "WK", "team": "SRH", "credits": 8.0},
    {"id": 119, "name": "Pat Cummins", "role": "BOWL", "team": "SRH", "credits": 9.5},
    {"id": 120, "name": "Abhishek Sharma", "role": "AR", "team": "SRH", "credits": 9.5},
    {"id": 121, "name": "Travis Head", "role": "BAT", "team": "SRH", "credits": 9.5},
    {"id": 122, "name": "Nitish Kumar Reddy", "role": "AR", "team": "SRH", "credits": 9.0},
    {"id": 123, "name": "Mohammed Shami", "role": "BOWL", "team": "SRH", "credits": 9.0},
    {"id": 124, "name": "Ishan Kishan", "role": "WK", "team": "SRH", "credits": 8.0},
    {"id": 125, "name": "Harshal Patel", "role": "BOWL", "team": "SRH", "credits": 8.5},
    {"id": 126, "name": "Rahul Chahar", "role": "BOWL", "team": "SRH", "credits": 8.0},
    {"id": 127, "name": "Adam Zampa", "role": "BOWL", "team": "SRH", "credits": 9.0},
    {"id": 128, "name": "Abhinav Manohar", "role": "BAT", "team": "SRH", "credits": 9.5},
]

PLAYERS_BY_ID = {p['id']: p for p in PLAYERS}

USERS = {}
DRAFTS = {}
LOCKED_TEAMS = {}
BUDGET_LIMIT = 100.0
MAX_PLAYERS = 12
